- name: Build, save, and deploy Docker container to remote server
  hosts: localhost
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  tasks:
    - name: Build the Docker image locally
      command: docker build -t express /home/useradmin/infra-setup-azure/
      args:
        chdir: /home/useradmin/infra-setup-azure/ 
        
    - name: Run the Docker container for the Express app
      docker_container:
        name: express
        image: express
        state: started
        ports:
          - "3000:3000"

    - name: Save the Docker image to a tar file
      command: docker save -o /home/useradmin/infra-setup-azure/express.tar express

- name: Transfer and deploy Docker container on remote server
  hosts: host
  become: true
  tasks:
    - name: Ensure Docker service is running on remote server
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Copy Docker image tar file to remote server
      copy:
        src: /home/useradmin/infra-setup-azure/express.tar     # Local path to the .tar file
        dest: /home/useradmin/express.tar        # Remote destination path
        mode: '0644'

    - name: Load Docker image from tar file on remote server
      command: docker load -i /home/useradmin/express.tar

    - name: Run the Docker container for the Express app
      docker_container:
        name: express
        image: express
        state: started
        ports:
          - "3000:3000"