- name: Deploy Express App Docker Container
  hosts: host
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image
      copy:
        src: "{{ express_src }}"
        dest: /usr/src/app
        mode: 0755

    - name: Build Docker image on the server
      command: docker build -t express /usr/src/app/express

    - name: Run Docker container for sample app
      docker_container:
        name: express
        image: express
        state: started
        ports:
          - "3000:3000"
