# Build Stage
FROM node:20-alpine AS builder

WORKDIR /app
COPY package.json /app/
RUN npm install --only=production

# Copy source files after installing dependencies
COPY src /app/

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["node", "server.js"]
