parameters: 
- name: dockerFilePath 
  type: string 
- name: serviceName 
  type: string
- name: repository 
  type: string
- name: containerRegistry
  type: string
- name: tag
  type: string
steps: 
  - task: Docker@2 
    displayName: 'DockerBuild: Build ${{ parameters.serviceName }} docker image' 
    inputs: 
      command: build 
      repository: '${{ parameters.repository }}' 
      dockerfile: '${{ parameters.dockerFilePath }}' 
      containerRegistry: '${{ parameters.containerRegistry }}' 
      tags: '${{ parameters.tag }}' 

  - task: Docker@2 
    displayName: 'DockerPush: Push ${{ parameters.serviceName }} docker image to ACR' 
    inputs: 
      command: push 
      repository: '${{ parameters.repository }}' 
      containerRegistry: '${{ parameters.containerRegistry }}' 
      tags: '${{ parameters.tag }}' 