version: '3' 

services:
  app:
    build:
      context: ../docker 
      dockerfile: docker/Dockerfile 
    ports:
      - "3000:3000" 
    env_file:
      - .env 
  func:
    build:
      context: ../ 
      dockerfile: infra-setup-azure/docker/Dockerfile
    ports:
      - "8080:80" 
    env_file:
      - .env